export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PRODUCT_REQUESTED = "PRODUCT_REQUESTED";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";

export const PRODUCT_GET_REQUESTED = "PRODUCT_GET_REQUESTED";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";



// saga watcher

export const REQUESTED_LOGIN = "REQUESTED_LOGIN";
export const REQUESTED_SEARCH_PRODUCT = "REQUESTED_SEARCH_PRODUCT";
export const REQUESTED_GET_PRODUCT = "REQUESTED_GET_PRODUCT";


